version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: platziflix
      POSTGRES_PASSWORD: platziflix123
      POSTGRES_DB: platziflix_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgresql://platziflix:platziflix123@db:5432/platziflix_db
    depends_on:
      - db

volumes:
  postgres_data: 